# Generated by Django 4.1.2 on 2022-10-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_song_date_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
