# Generated by Django 4.1.2 on 2022-10-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_artiste_first_name_alter_artiste_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
